modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "isometric_renders"
version = "${version}"
displayName = "Isometric Renders"
authors = "glisco"
credits = ""
description = '''
Creates high-resolution renders of game objects
'''
logoFile = "assets/isometric_renders/icon.png"

[[accessTransformers]]
file = "META-INF/isometricrenders.accesstransformer.cfg"

[[mixins]]
config = "isometric-renders.mixins.json"

[[dependencies.isometric_renders]]
modId = "neoforge"
required = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.isometric_renders]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.isometric_renders]]
modId = "fabric_api"
required = true
versionRange = "[0.101.2+2.0.10+1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.isometric_renders]]
modId = "owo"
required = true
versionRange = "[0.12.15-beta.7+1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.isometric_renders]]
modId = "worldmesher"
required = true
versionRange = "[0.4.7+1.21,)"
ordering = "NONE"
side = "BOTH"